<?php
/**
 * The base configuration for WordPress
 *
 * The wp-config.php creation script uses this file during the
 * installation. You don't have to use the web site, you can
 * copy this file to "wp-config.php" and fill in the values.
 *
 * This file contains the following configurations:
 *
 * * MySQL settings
 * * Secret keys
 * * Database table prefix
 * * ABSPATH
 *
 * @link https://codex.wordpress.org/Editing_wp-config.php
 *
 * @package WordPress
 */

// ** MySQL settings ** //
/** The name of the database for WordPress */
define( 'DB_NAME', 'dbauLkHS3brZ' );

/** MySQL database username */
define( 'DB_USER', 'Bv6NIymXEM' );

/** MySQL database password */
define( 'DB_PASSWORD', 'Mxq5Tv3ORt' );

/** MySQL hostname */
define( 'DB_HOST', 'localhost' );

/** Database Charset to use in creating database tables. */
define( 'DB_CHARSET', 'utf8' );

/** The Database Collate type. Don't change this if in doubt. */
define( 'DB_COLLATE', '' );

/**
 * Authentication Unique Keys and Salts.
 *
 * Change these to different unique phrases!
 * You can generate these using the {@link https://api.wordpress.org/secret-key/1.1/salt/ WordPress.org secret-key service}
 * You can change these at any point in time to invalidate all existing cookies. This will force all users to have to log in again.
 *
 * @since 2.6.0
 */

/**
 * WordPress Database Table prefix.
 *
 * You can have multiple installations in one database if you give each
 * a unique prefix. Only numbers, letters, and underscores please!
 */
$table_prefix = 'wp_';


/*
 * IMPORTANT
 * THIS IS NOT A STANDARD WP-CONFIG FILE
 * CHANGES SHOULD GO IN my-config.php
 * /var/www/vhosts/triggermovement.com/httpdocs/my-config.php
 * DO NOT EDIT THIS FILE, IT WILL BE OVERRIDEN
 * https://www.34sp.com/kb/128/wordpress-hosting-file-structure
 *
 */

define('AUTH_KEY',         'ba0a8f970c8211518c6ed96bf7fb4c9f');
define('SECURE_AUTH_KEY',  '4b93c71e6d0cdc41ac8b883cdeb0f231');
define('LOGGED_IN_KEY',    '0365ea59a1f09f2715b1ffa6a997bdf2');
define('NONCE_KEY',        '9c52211ed8651eafc2964d8be331df96');
define('AUTH_SALT',        'e6e7d0b36056eb5f3e4c9b032c6b85b5');
define('SECURE_AUTH_SALT', 'bf0585feb31ee66325267508ff070ef9');
define('LOGGED_IN_SALT',   '1ce957c32f6b74ef44cad5d4caacabf4');
define('NONCE_SALT',       '0b3c3448c513db6eba132a96e930150a');

define('WP_CACHE', true);
if (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https') {
    define('FORCE_SSL_ADMIN', true);
    $_SERVER['HTTPS'] = 'on';
}
//Disable WordPress trying to update itself
define( 'WP_AUTO_UPDATE_CORE', false );

define('FS_METHOD', 'direct');
define( 'DISALLOW_FILE_EDIT', true );
define('WP_CONTENT_DIR', '/var/www/vhosts/triggermovement.com/httpdocs/wp-content');
define('WP_CACHE_KEY_SALT', '88e622981c15a0dac1896123b064dbe5');

require_once('/var/www/vhosts/triggermovement.com/httpdocs/my-config.php');

if(!defined('DISABLE_WP_CRON')) {
    define('DISABLE_WP_CRON', true);
}


/* That's all, stop editing! Happy blogging. */

/** Absolute path to the WordPress directory. */
if ( ! defined( 'ABSPATH' ) )
	define( 'ABSPATH', dirname( __FILE__ ) . '/' );

/** Sets up WordPress vars and included files. */
require_once ABSPATH . 'wp-settings.php';
